// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwjgeruhmorofdobccqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3amdlcnVobW9yb2Zkb2JjY3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzQ5MjUsImV4cCI6MjA1OTQ1MDkyNX0._3pUjP4o2t61Uvq1j3EXzdB_M7DHTqfY66VfMMvHEWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);